FROM golang

RUN mkdir /dreamgo
RUN mkdir /dreamgo/log
ADD ./bin /dreamgo/bin
ADD conf /dreamgo/conf
ADD ./static /dreamgo/static
ADD ./template /dreamgo/template

EXPOSE 2017

WORKDIR /dreamgo

# Define default command.
ENTRYPOINT [ "./bin/dreamgo" ]
